import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import tailwindcss from '@tailwindcss/vite'
import vue from '@vitejs/plugin-vue'
import vueDevTools from 'vite-plugin-vue-devtools'
import prerender from 'vite-plugin-prerenderer'

const prerenderRoutes = [
  '/',
  '/generation/1',
  '/generation/2',
  '/generation/3',
  '/generation/4',
  '/generation/5',
  '/generation/6',
  '/generation/7',
  '/generation/8',
  '/generation/9',
  '/privacy',
  '/terms',
  '/pokemon/pikachu',
  '/pokemon/raichu',
  '/pokemon/eevee',
  '/pokemon/vaporeon',
  '/pokemon/jolteon',
  '/pokemon/flareon',
  '/pokemon/espeon',
  '/pokemon/umbreon',
  '/pokemon/leafeon',
  '/pokemon/glaceon',
  '/pokemon/sylveon',
  '/pokemon/charizard',
  '/pokemon/charmander',
  '/pokemon/charmeleon',
  '/pokemon/venusaur',
  '/pokemon/bulbasaur',
  '/pokemon/ivysaur',
  '/pokemon/blastoise',
  '/pokemon/squirtle',
  '/pokemon/wartortle',
  '/pokemon/mewtwo',
  '/pokemon/mew',
  '/pokemon/articuno',
  '/pokemon/zapdos',
  '/pokemon/moltres',
  '/pokemon/lugia',
  '/pokemon/ho-oh',
  '/pokemon/raikou',
  '/pokemon/entei',
  '/pokemon/suicune',
  '/pokemon/celebi',
  '/pokemon/rayquaza',
  '/pokemon/kyogre',
  '/pokemon/groudon',
  '/pokemon/latios',
  '/pokemon/latias',
  '/pokemon/jirachi',
  '/pokemon/deoxys',
  '/pokemon/dialga',
  '/pokemon/palkia',
  '/pokemon/giratina',
  '/pokemon/arceus',
  '/pokemon/darkrai',
  '/pokemon/shaymin',
  '/pokemon/reshiram',
  '/pokemon/zekrom',
  '/pokemon/kyurem',
  '/pokemon/landorus',
  '/pokemon/tornadus',
  '/pokemon/thundurus',
  '/pokemon/xerneas',
  '/pokemon/yveltal',
  '/pokemon/zygarde',
  '/pokemon/diancie',
  '/pokemon/hoopa',
  '/pokemon/volcanion',
  '/pokemon/solgaleo',
  '/pokemon/lunala',
  '/pokemon/necrozma',
  '/pokemon/tapu-koko',
  '/pokemon/tapu-lele',
  '/pokemon/tapu-bulu',
  '/pokemon/tapu-fini',
  '/pokemon/melmetal',
  '/pokemon/meltan',
  '/pokemon/zacian',
  '/pokemon/zamazenta',
  '/pokemon/eternatus',
  '/pokemon/calyrex',
  '/pokemon/miraidon',
  '/pokemon/koraidon',
  '/pokemon/iron-valiant',
  '/pokemon/roaring-moon',
  '/pokemon/charcadet',
  '/pokemon/ceruledge',
  '/pokemon/armarouge',
  '/pokemon/greninja',
  '/pokemon/lucario',
  '/pokemon/gengar',
  '/pokemon/snorlax',
  '/pokemon/gardevoir',
  '/pokemon/dragonite',
  '/pokemon/salamence',
  '/pokemon/metagross',
  '/pokemon/tyranitar',
  '/pokemon/garchomp',
  '/pokemon/coalossal',
  '/pokemon/cinderace',
  '/pokemon/inteleon',
  '/pokemon/rillaboom',
  '/pokemon/decidueye',
  '/pokemon/primarina',
  '/pokemon/incineroar',
  '/pokemon/chesnaught',
  '/pokemon/delphox',
  '/pokemon/greninja',
  '/pokemon/feraligatr',
  '/pokemon/typhlosion',
  '/pokemon/meganium',
  '/pokemon/blaziken',
  '/pokemon/sceptile',
  '/pokemon/swampert',
  '/pokemon/infernape',
  '/pokemon/empoleon',
  '/pokemon/torterra',
  '/pokemon/serperior',
  '/pokemon/emboar',
  '/pokemon/samurott',
  '/pokemon/decidueye-hisui',
  '/pokemon/typhlosion-hisui',
  '/pokemon/samurott-hisui',
  '/pokemon/ursaluna',
  '/pokemon/baxcalibur',
  '/pokemon/annihilape',
  '/pokemon/tinkaton',
]


// https://vite.dev/config/
export default defineConfig({
  base: '/pokegen/',
  plugins: [
    vue(),
    vueDevTools(),
    tailwindcss(),
    prerender({
      routes: prerenderRoutes,
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    },
  },
})
