/**
 * Codici di errore applicativi standardizzati.
 */
export enum ApplicationErrorCode {
  EXTERNAL_SERVICE_UNAVAILABLE = "EXTERNAL_SERVICE_UNAVAILABLE",
  NOT_FOUND = "NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  MAPPING_ERROR = "MAPPING_ERROR",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  SERVICE_ERROR  = "SERVICE_ERROR"
}
